name: PHP Composer (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # 1. Construction de l'image à partir de ton Dockerfile
      - name: Build Docker image
        run: docker build -t php -f docker/php/Dockerfile .
      
      # 2. Validation Composer via Docker
      - name: Validate composer.json
        run: docker run --rm php composer validate --strict
      
      # 3. Installation des dépendances
      # On monte le dossier courant pour que le vendor soit créé/accessible
      - name: Install dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/var/www/html -w /var/www/html php composer install --prefer-dist --no-progress
      
      # 4. Exécution des tests et analyses
      - name: Run PHPCS
        run: docker run --rm -v ${{ github.workspace }}:/var/www/html -w /var/www/html php composer run phpcs

      - name: Run PHPStan
        run: docker run --rm -v ${{ github.workspace }}:/var/www/html -w /var/www/html php composer run phpstan

      - name: Run Unit Test
        run: docker run --rm -v ${{ github.workspace }}:/var/www/html -w /var/www/html php php bin/phpunit